const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 20,
      coutInStock: 10,
      brank: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'Puma Slim shirt',
      slug: 'Puma-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 20,
      coutInStock: 10,
      brank: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'Adidas Slim shirt',
      slug: 'Adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 20,
      coutInStock: 10,
      brank: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'diadora Slim shirt',
      slug: 'diadora-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 20,
      coutInStock: 10,
      brank: 'diadora',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
  ],
};

export default data;
